Repository aehrc/pathling, pull requests merged in 2021-07, with the labels that each got.

#317 Sum function and combine operator
  fhir-server/src/main/antlr4/au/csiro/pathling/fhirpath/parser/generated/FhirPath.g4
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/FhirPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/NonLiteralPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/ResourcePath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/UntypedResourcePath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/element/BooleanPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/element/CodingPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/element/DatePath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/element/DateTimePath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/element/DecimalPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/element/ElementPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/element/IntegerPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/element/ReferencePath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/element/StringPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/element/TimePath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/function/AggregateFunction.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/function/IifFunction.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/function/NamedFunction.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/function/SumFunction.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/literal/BooleanLiteralPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/literal/CodingLiteralPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/literal/DateLiteralPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/literal/DateTimeLiteralPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/literal/DecimalLiteralPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/literal/IntegerLiteralPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/literal/LiteralPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/literal/NullLiteralPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/literal/StringLiteralPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/literal/TimeLiteralPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/operator/CombineOperator.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/operator/Operator.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/parser/Visitor.java
  fhir-server/src/test/java/au/csiro/pathling/fhirpath/CanBeCombinedWithTest.java
  fhir-server/src/test/java/au/csiro/pathling/fhirpath/function/IifFunctionTest.java
  fhir-server/src/test/java/au/csiro/pathling/fhirpath/function/SumFunctionTest.java
  fhir-server/src/test/java/au/csiro/pathling/fhirpath/function/subsumes/SubsumesFunctionTest.java
  fhir-server/src/test/java/au/csiro/pathling/fhirpath/operator/CombineOperatorTest.java
  fhir-server/src/test/java/au/csiro/pathling/fhirpath/parser/ParserTest.java
  fhir-server/src/test/java/au/csiro/pathling/security/SecurityTestForResources.java
  fhir-server/src/test/java/au/csiro/pathling/test/assertions/BaseFhirPathAssertion.java
  fhir-server/src/test/java/au/csiro/pathling/test/assertions/ElementPathAssertion.java
  fhir-server/src/test/java/au/csiro/pathling/test/assertions/FhirPathAssertion.java
  fhir-server/src/test/java/au/csiro/pathling/test/assertions/LiteralPathAssertion.java
  fhir-server/src/test/java/au/csiro/pathling/test/assertions/ResourcePathAssertion.java
  fhir-server/src/test/java/au/csiro/pathling/test/assertions/UntypedResourcePathAssertion.java
  fhir-server/src/test/java/au/csiro/pathling/test/builders/DatasetBuilder.java
  fhir-server/src/test/resources/responses/ParserTest/testCombineOperator.csv
  fhir-server/src/test/resources/responses/ParserTest/testCombineOperatorWithComplexTypeAndNull.csv
  fhir-server/src/test/resources/responses/ParserTest/testCombineOperatorWithDifferentlyTypedStringPaths.csv
  fhir-server/src/test/resources/responses/ParserTest/testCombineOperatorWithResourcePaths.csv
  fhir-server/src/test/resources/responses/ParserTest/testCombineOperatorWithWhereFunction.csv
  site/.gitignore
  site/docs/fhirpath/data-types.md
  site/docs/fhirpath/functions.md
  site/docs/fhirpath/operators.md
Labels: new feature

#315 Changed Coding equality to compare all fields except for `id`.
  fhir-server/src/main/antlr4/au/csiro/pathling/fhirpath/parser/generated/FhirPath.g4
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/element/CodingPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/encoding/CodingEncoding.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/encoding/ImmutableCoding.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/literal/CodingLiteral.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/literal/CodingLiteralPath.java
  fhir-server/src/main/java/au/csiro/pathling/spark/Spark.java
  fhir-server/src/main/java/au/csiro/pathling/spark/udf/CodingsEqual.java
  fhir-server/src/test/java/au/csiro/pathling/aggregate/AggregateQueryTest.java
  fhir-server/src/test/java/au/csiro/pathling/fhirpath/literal/CodingLiteralPathTest.java
  fhir-server/src/test/java/au/csiro/pathling/fhirpath/literal/CodingLiteralTest.java
  fhir-server/src/test/java/au/csiro/pathling/fhirpath/operator/EqualityOperatorCodingTest.java
  fhir-server/src/test/java/au/csiro/pathling/fhirpath/operator/MembershipOperatorTest.java
  fhir-server/src/test/java/au/csiro/pathling/fhirpath/parser/ParserTest.java
  fhir-server/src/test/java/au/csiro/pathling/test/fixtures/CodingRowFixture.java
  fhir-server/src/test/java/au/csiro/pathling/test/helpers/SparkHelpers.java
  fhir-server/src/test/resources/responses/AggregateQueryTest/queryWithWhereAndMembership.Parameters.json
  fhir-server/src/test/resources/responses/AggregateQueryTest/queryWithWhereAsComparisonOperand.Parameters.json
  fhir-server/src/test/resources/responses/AggregateQueryTest/queryWithWhereInAggregation.Parameters.json
  fhir-server/src/test/resources/responses/GroupingLiteralTest/CodingLiteral.Parameters.json
  fhir-server/src/test/resources/responses/ParserTest/testIfFunction.csv
  fhir-server/src/test/resources/responses/ParserTest/testWithCodingLiteral.csv
Labels: breaking change, bug

#323 Add lock to prevent parallel import operations
  fhir-server/src/main/java/au/csiro/pathling/update/ImportLock.java
Labels: bug

#328 Implement anyTrue, anyFalse, allTrue, allFalse
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/function/BooleansTestFunction.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/function/NamedFunction.java
  fhir-server/src/test/java/au/csiro/pathling/fhirpath/function/BooleansTestFunctionTest.java
  site/docs/fhirpath/functions.md
Labels: new feature

#329 Implements custom encoded type support in choices
  encoders/src/main/scala/au/csiro/pathling/encoders/EncoderBuilder.scala
  encoders/src/main/scala/au/csiro/pathling/encoders/SchemaConverter.scala
  encoders/src/main/scala/au/csiro/pathling/encoders/datatypes/CustomCoder.scala
  encoders/src/main/scala/au/csiro/pathling/encoders/datatypes/DataTypeMappings.scala
  encoders/src/main/scala/au/csiro/pathling/encoders/datatypes/DecimalCustomCoder.scala
  encoders/src/main/scala/au/csiro/pathling/encoders/datatypes/IdCustomCoder.scala
  encoders/src/main/scala/au/csiro/pathling/encoders/datatypes/R4DataTypeMappings.scala
  encoders/src/test/java/au/csiro/pathling/encoders/FhirEncodersTest.java
  encoders/src/test/java/au/csiro/pathling/encoders/SchemaConverterTest.java
  encoders/src/test/java/au/csiro/pathling/encoders/TestData.java
  pom.xml
  site/docs/fhirpath/data-types.md
Labels: bug

#335 Fix problem with encoding of answers within QuestionnaireResponse
  encoders/src/main/scala/au/csiro/pathling/encoders/datatypes/R4DataTypeMappings.scala
  encoders/src/test/java/au/csiro/pathling/encoders/FhirEncodersTest.java
  encoders/src/test/java/au/csiro/pathling/encoders/SchemaConverterTest.java
  encoders/src/test/java/au/csiro/pathling/encoders/TestData.java
Labels: bug

#337 Add canonical and url to primitive type map
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/element/ElementDefinition.java
  fhir-server/src/test/java/au/csiro/pathling/aggregate/AggregateQueryTest.java
  fhir-server/src/test/resources/responses/AggregateQueryTest/queryWithCanonicalGrouping.Parameters.json
Labels: bug

#331 Prevent joins involving literal paths
  fhir-server/src/main/java/au/csiro/pathling/QueryHelpers.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/FhirPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/NonLiteralPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/ResourcePath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/UntypedResourcePath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/literal/LiteralPath.java
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/operator/CombineOperator.java
  fhir-server/src/test/java/au/csiro/pathling/fhirpath/operator/ComparisonOperatorTest.java
  fhir-server/src/test/java/au/csiro/pathling/fhirpath/operator/MathOperatorTest.java
  fhir-server/src/test/java/au/csiro/pathling/fhirpath/parser/ParserTest.java
  fhir-server/src/test/java/au/csiro/pathling/test/builders/DatasetBuilder.java
  fhir-server/src/test/resources/responses/ParserTest/testCombineOperatorWithTwoLiterals.csv
  fhir-server/src/test/resources/responses/ParserTest/testCombineOperatorWithTwoUntypedResourcePaths.csv
Labels: optimisation

#343 Fix lookup of List resource using class passed from HAPI operation
  fhir-server/src/main/java/au/csiro/pathling/fhirpath/ResourceDefinition.java
  fhir-server/src/main/java/au/csiro/pathling/search/CachingSearchProvider.java
  fhir-server/src/main/java/au/csiro/pathling/search/SearchProvider.java
Labels: bug
