Repository aehrc/pathling, pull requests merged in 2022-06, with the labels that each got.

#494 Python API for encoders.
  .editorconfig
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  .gitignore
  encoders/pom.xml
  encoders/src/main/java/au/csiro/pathling/api/EncodeMapPartitionFunc.java
  encoders/src/main/java/au/csiro/pathling/api/FhirMimeTypes.java
  encoders/src/main/java/au/csiro/pathling/api/PathlingContext.java
  encoders/src/main/java/au/csiro/pathling/support/FhirConversionSupport.java
  encoders/src/main/java/au/csiro/pathling/support/r4/R4FhirConversionSupport.java
  encoders/src/test/java/au/csiro/pathling/api/PathlingContextTest.java
  encoders/src/test/java/au/csiro/pathling/encoders/SchemaAsserts.java
  encoders/src/test/java/au/csiro/pathling/encoders/SchemaConverterTest.java
  encoders/src/test/resources/data/bundles/R4/json/Bennett146_Swaniawski813_704c9750-f6e6-473b-ee83-fbd48e07fe3f.json
  encoders/src/test/resources/data/bundles/R4/json/Bennie663_Raynor401_46d8cf9a-63e3-43bc-1241-3a01f198fe87.json
  encoders/src/test/resources/data/bundles/R4/json/Chanell45_Ratke343_f924fd7f-5920-5bdc-cd40-bb434aff1051.json
  encoders/src/test/resources/data/bundles/R4/json/Dino214_Parisian75_40d82b80-b682-cd8b-da6d-396809878641.json
  encoders/src/test/resources/data/bundles/R4/json/Horacio317_Macejkovic424_f6976bcd-a6ff-c7a5-d6c7-89f673fca423.json
  encoders/src/test/resources/data/bundles/R4/xml/Bennett146_Swaniawski813_704c9750-f6e6-473b-ee83-fbd48e07fe3f.xml
  encoders/src/test/resources/data/bundles/R4/xml/Bennie663_Raynor401_46d8cf9a-63e3-43bc-1241-3a01f198fe87.xml
  encoders/src/test/resources/data/bundles/R4/xml/Chanell45_Ratke343_f924fd7f-5920-5bdc-cd40-bb434aff1051.xml
  encoders/src/test/resources/data/bundles/R4/xml/Dino214_Parisian75_40d82b80-b682-cd8b-da6d-396809878641.xml
  encoders/src/test/resources/data/bundles/R4/xml/Horacio317_Macejkovic424_f6976bcd-a6ff-c7a5-d6c7-89f673fca423.xml
  encoders/src/test/resources/data/resources/R4/json/Condition.ndjson
  encoders/src/test/resources/data/resources/R4/json/Observation.ndjson
  encoders/src/test/resources/data/resources/R4/json/Patient.ndjson
  encoders/src/test/resources/data/resources/R4/json/Questionnaire.ndjson
  fhir-server/pom.xml
  fhir-server/src/main/java/au/csiro/pathling/async/SparkListener.java
  lib/import/pom.xml
  lib/js/pom.xml
  lib/python/LICENSE.md
  lib/python/MANIFEST.in
  lib/python/README.md
  lib/python/docs/templates/conf.py_t
  lib/python/examples/data/bundles/Bennett146_Swaniawski813_704c9750-f6e6-473b-ee83-fbd48e07fe3f.json
  lib/python/examples/data/bundles/Dino214_Parisian75_40d82b80-b682-cd8b-da6d-396809878641.json
  lib/python/examples/data/resources/Condition.ndjson
  lib/python/examples/data/resources/Patient.ndjson
  lib/python/examples/encode_bundle.py
  lib/python/examples/encode_resources.py
  lib/python/pathling/__init__.py
  lib/python/pathling/context.py
  lib/python/pathling/etc.py
  lib/python/pathling/fhir.py
  lib/python/pom.xml
  lib/python/requirements.txt
  lib/python/requirements/dev.txt
  lib/python/requirements/package.txt
  lib/python/setup.cfg
  lib/python/setup.py
  lib/python/tests/test_pathling.py
  pom.xml
  site/.gitignore
  site/_includes/nav.html
  site/pom.xml
Labels: new feature

#584 v5.1.1
  .github/workflows/test.yml
  LICENSE.md
  README.md
  encoders/pom.xml
  encoders/src/license/THIRD-PARTY.properties
  fhir-server/pom.xml
  fhir-server/src/license/THIRD-PARTY.properties
  fhir-server/src/test/java/au/csiro/pathling/test/TestDataImporter.java
  lib/import/package-lock.json
  lib/import/package.json
  lib/import/pom.xml
  lib/js/package-lock.json
  lib/js/package.json
  lib/js/pom.xml
  lib/python/examples/encode_bundle.py
  lib/python/examples/encode_resources.py
  lib/python/pom.xml
  lib/python/requirements/dev.txt
  lib/python/requirements/package.txt
  lib/python/tests/test_pathling.py
  licenses/apache license, version 2.0 - apache2.0.html
  licenses/mit - mit-license.html
  licenses/the json license - license.html
  pom.xml
  site/docs/index.md
  site/docs/server/authorization.md
  site/docs/server/index.md
  site/docs/server/operations/aggregate.md
  site/docs/server/operations/extract.md
  site/docs/server/operations/import.md
  site/docusaurus.config.js
  site/pom.xml
  site/src/images/aggregate-dark.svg
  site/src/images/aggregate.svg
  site/src/images/architecture-dark.svg
  site/src/images/architecture.svg
  site/src/images/authorities-dark.svg
  site/src/images/authorities.svg
  site/src/images/components-dark.svg
  site/src/images/components.svg
  site/src/images/extract-dark.svg
  site/src/images/extract.svg
  site/src/images/import-dark.svg
  site/src/images/import.svg
  site/src/images/operations-dark.svg
  site/src/images/operations.svg
  site/static/assets/images/leaves.jpg
  site/static/assets/images/leaves@2x.jpg
  site/static/assets/images/logo-colour-dark.svg
  site/static/assets/images/logo-colour-detail.svg
  site/static/assets/images/logo-colour.svg
  site/static/assets/images/logo-mono.svg
  site/static/assets/images/social-preview.png
  site/static/index.html
Labels: release

#596 Split test suite into tranches
  .github/workflows/test.yml
  fhir-server/pom.xml
  fhir-server/src/test/java/au/csiro/pathling/aggregate/AggregateQueryTest.java
  fhir-server/src/test/java/au/csiro/pathling/extract/ExtractQueryTest.java
  fhir-server/src/test/java/au/csiro/pathling/security/ga4gh/ManifestConverterTest.java
  fhir-server/src/test/java/au/csiro/pathling/test/integration/AsyncSecurityTest.java
  fhir-server/src/test/java/au/csiro/pathling/test/integration/AsyncTest.java
  fhir-server/src/test/java/au/csiro/pathling/test/integration/AuthorizationConfigurationTest.java
  fhir-server/src/test/java/au/csiro/pathling/test/integration/CachedSearchTest.java
  fhir-server/src/test/java/au/csiro/pathling/test/integration/CapabilityStatementTest.java
  fhir-server/src/test/java/au/csiro/pathling/test/integration/ExtractSecurityTest.java
  fhir-server/src/test/java/au/csiro/pathling/test/integration/ExtractTest.java
  fhir-server/src/test/java/au/csiro/pathling/test/integration/MultipleAggregationsAndResolveTest.java
  fhir-server/src/test/java/au/csiro/pathling/test/integration/SearchTest.java
  fhir-server/src/test/java/au/csiro/pathling/test/integration/SentryTest.java
  fhir-server/src/test/java/au/csiro/pathling/test/integration/TerminologyServiceIntegrationTest.java
  fhir-server/src/test/java/au/csiro/pathling/test/integration/modification/ModificationTest.java
Labels: testing

#621 v5.2.0
  .github/workflows/combine-prs.yml
  .github/workflows/test.yml
  LICENSE.md
  encoders/pom.xml
  fhir-server/pom.xml
  fhir-server/src/license/THIRD-PARTY.properties
  lib/import/package-lock.json
  lib/import/package.json
  lib/import/pom.xml
  lib/js/package-lock.json
  lib/js/package.json
  lib/js/pom.xml
  lib/python/pathling/context.py
  lib/python/pom.xml
  lib/python/requirements/package.txt
  lib/python/setup.py
  lib/python/tests/test_pathling.py
  licenses/apache license, version 2.0 - apache2.0.html
  licenses/gnu general public license (gpl), version 2, with the classpath exception - gplv2+ce.html
  licenses/mit - mit-license.html
  licenses/the json license - license.html
  pom.xml
  site/docs/encoders/index.md
  site/pom.xml
  site/src/components/installation.jsx
Labels: release
