Repository aehrc/pathling, pull requests merged in 2025-06, with the labels that each got.

#2364 Pre-install spark distribution for CI sparkly from our mirror.
  .github/workflows/test.yml
Labels: bug, ci

#2369 Remove a number of obsolete classes.
  fhirpath/src/main/java/au/csiro/pathling/QueryExecutor.java
  fhirpath/src/main/java/au/csiro/pathling/QueryHelpers.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/AbstractPath.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/CalendarDurationUtils.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/ColumnHelpers.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/FhirPath.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/FhirPathAndContext.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/FhirPathConstants.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/FhirPathDurationUnit.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/FhirPathStreamVisitor.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/FhirPathVisitor.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/LegacyEvaluationContext.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/Materializable.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/Nesting.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/NestingKey.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/Orderable.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/Referrer.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/BooleanCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/CodingCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/DateCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/DateTimeCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/DecimalCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/IntegerCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/StringCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/TimeCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/MethodDefinedFunction.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/parser/Parser.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/path/Paths.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/NonLiteralPathTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/OrderableTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/BooleansTestFunctionTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/CountFunctionTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/EmptyFunctionTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/ExistsFunctionTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/ExtensionFunctionTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/FirstFunctionTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/IifFunctionTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/NotFunctionTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/OfTypeFunctionTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/ResolveFunctionTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/ReverseResolveFunctionTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/SumFunctionTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/UntilFunctionTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/WhereFunctionTest.java
  fhirpath/src/test/java/au/csiro/pathling/test/builders/DatasetBuilder.java
  fhirpath/src/test/java/au/csiro/pathling/test/builders/ElementPathBuilder.java
  fhirpath/src/test/java/au/csiro/pathling/test/builders/EvaluationContextBuilder.java
Labels: refactoring, deprecation

#2397 Adding testing coverage for the supported FHIRpath functions.
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/definition/def/DefChoiceDefinition.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/FunctionParameterResolver.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/MethodDefinedFunction.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/BooleanLogicFunctionsDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/FhirFunctionsDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/FilteringAndProjectionFunctionsDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/JoinKeyFunctionsDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/SubsettingFunctionsDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/FunctionParameterResolverTest.java
  fhirpath/src/test/java/au/csiro/pathling/test/dsl/DisplayFunctionDslTestSetup.java
  fhirpath/src/test/java/au/csiro/pathling/test/dsl/FhirPathTestBuilder.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlSpecTestBase.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlSupport.java
  fhirpath/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Labels: testing, refactoring

#2400 FIxing traversal to choice fields for JSON datasource.
  encoders/src/main/scala/au/csiro/pathling/encoders/Expressions.scala
  encoders/src/main/scala/au/csiro/pathling/encoders/SerializerBuilder.scala
  encoders/src/test/java/au/csiro/pathling/encoders/FhirEncodersTest.java
  library-api/src/test/java/au/csiro/pathling/library/io/DataSourcesTest.java
Labels: bug

#2402 Implement join() function.
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/provider/StringFunctions.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/registry/StaticFunctionRegistry.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/StringFunctionsDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/execution/SingleResourceFhirpathTest.java
Labels: new feature

#2403 Implement boolean evaluation of collections.
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/BooleanCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/Collection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/EmptyCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/mixed/ChoiceElementCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/column/ColumnRepresentation.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/FunctionParameterResolver.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/operator/BooleanOperator.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/BooleanLogicFunctionsDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/FilteringAndProjectionFunctionsDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/PathsDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/SystemDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/FunctionParameterResolverTest.java
Labels: bug, new feature, fhirpath

#2404 Add support for traversal into Coding literals and Unicode escape sequences for String literal
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/CodingCollection.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/FilteringAndProjectionFunctionsDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/SystemDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/literal/StringLiteralPathTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/yaml/YamlFhirpathTest.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlSupport.java
  fhirpath/src/test/resources/fhirpath-ptl/cases/literals.yaml
  utilities/src/main/java/au/csiro/pathling/fhirpath/literal/StringLiteral.java
Labels: new feature, fhirpath

#2407 Implement + operator on Strings and correct handling of explicit empty collection in math operations.
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/Numeric.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/Collection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/EmptyCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/StringCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/column/ColumnRepresentation.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/operator/BinaryOperator.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/operator/MathOperator.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/MathOperatorsDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/yaml/YamlFhirpathTest.java
  fhirpath/src/test/resources/fhirpath-ptl/cases/misc.yaml
  terminology/src/main/java/au/csiro/pathling/terminology/DefaultTerminologyService.java
Labels: bug, new feature, fhirpath

#2423 Fixing the issue with rendering of empty columns in fhir view.
  fhirpath/src/main/java/au/csiro/pathling/view/Projection.java
  fhirpath/src/test/resources/viewTests/misc.json
Labels: bug

#2419 Improve view definition validation errors
  fhirpath/src/main/java/au/csiro/pathling/views/Column.java
  fhirpath/src/main/java/au/csiro/pathling/views/ColumnSelect.java
  fhirpath/src/main/java/au/csiro/pathling/views/ConstantDeclaration.java
  fhirpath/src/main/java/au/csiro/pathling/views/FhirView.java
  fhirpath/src/main/java/au/csiro/pathling/views/FhirViewExecutor.java
  fhirpath/src/main/java/au/csiro/pathling/views/ForEachOrNullSelect.java
  fhirpath/src/main/java/au/csiro/pathling/views/ForEachSelect.java
  fhirpath/src/main/java/au/csiro/pathling/views/SelectClause.java
  fhirpath/src/main/java/au/csiro/pathling/views/SelectClauseTypeAdapter.java
  fhirpath/src/main/java/au/csiro/pathling/views/SelectClauseTypeAdapterFactory.java
  fhirpath/src/main/java/au/csiro/pathling/views/WhereClause.java
  fhirpath/src/main/java/au/csiro/pathling/views/validation/AtMostOneNonNull.java
  fhirpath/src/main/java/au/csiro/pathling/views/validation/AtMostOneNonNullValidator.java
  fhirpath/src/main/java/au/csiro/pathling/views/validation/CompatibleUnionColumns.java
  fhirpath/src/main/java/au/csiro/pathling/views/validation/CompatibleUnionColumnsValidator.java
  fhirpath/src/main/java/au/csiro/pathling/views/validation/UniqueColumnNames.java
  fhirpath/src/main/java/au/csiro/pathling/views/validation/UniqueColumnNamesValidator.java
  fhirpath/src/main/java/au/csiro/pathling/views/validation/ValidName.java
  fhirpath/src/test/java/au/csiro/pathling/UnitTestDependencies.java
  fhirpath/src/test/java/au/csiro/pathling/views/FhirViewExecutorTest.java
  fhirpath/src/test/java/au/csiro/pathling/views/FhirViewValidationTest.java
  library-api/src/main/java/au/csiro/pathling/library/PathlingContext.java
Labels: bug

#2377 Update reference implementation test config to match v8 scope
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/parser/TermVisitor.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/path/Literals.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/yaml/YamlReferenceImplTest.java
  fhirpath/src/test/java/au/csiro/pathling/test/dsl/FhirPathTestBuilder.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/FhipathTestSpec.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/TestConfig.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlSpecTestBase.java
  fhirpath/src/test/resources/fhirpath-js/config.yaml
Labels: testing

#2435 Implement 'ofType()' for fhirpath (System) types in polymorphic collections.
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/FhirPathType.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/Collection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/mixed/ChoiceElementCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/column/ColumnRepresentation.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/FilteringAndProjectionFunctionsDslTest.java
Labels: bug, new feature

#2436 Updating required spark version to 3.5.2
  fhirpath/src/test/resources/viewTests/misc.json
  lib/python/requirements/package.txt
  lib/python/setup.py
  lib/python/tests/test_view.py
Labels: bug

#2433 Refactor CI build to be aligned to modules
  .github/workflows/test.yml
  encoders/pom.xml
  fhirpath/pom.xml
  lib/R/pom.xml
  pom.xml
  site/pom.xml
  terminology/pom.xml
  utilities/pom.xml
Labels: ci

#2440 Test against all search parameter expressions in the FHIR spec
  fhirpath/src/test/java/au/csiro/pathling/test/BulkExpressionParsingTest.java
  fhirpath/src/test/resources/search-params.txt
Labels: testing, fhirpath
