Repository aehrc/pathling, pull requests merged in 2025-07, with the labels that each got.

#2442 Enhance testing framework to assert failures on exclusions
  .github/workflows/test.yml
  fhirpath/src/main/antlr4/au/csiro/pathling/fhirpath/parser/generated/FhirPath.g4
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/StringCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/operator/BinaryOperatorType.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/parser/InvocationVisitor.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/parser/TypeSpecifierVisitor.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/parser/Visitor.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/path/Literals.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/path/Paths.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/variable/UnsupportedVariableResolver.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/variable/VariableResolverChain.java
  fhirpath/src/main/java/au/csiro/pathling/sql/SqlFunctions.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/MathOperatorsDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/yaml/YamlFhirpathTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/yaml/YamlReferenceImplTest.java
  fhirpath/src/test/java/au/csiro/pathling/test/BulkExpressionParsingTest.java
  fhirpath/src/test/java/au/csiro/pathling/test/dsl/FhirPathDslTestBase.java
  fhirpath/src/test/java/au/csiro/pathling/test/dsl/FhirPathTestBuilder.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/FhipathTestSpec.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/JsonColumnWriter.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/TestConfig.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlCachedTestBase.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlConfig.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlSpec.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlSpecCachedTestBase.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlSpecTest.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlSpecTestBase.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlSupport.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlTestArgumentProvider.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlTestBase.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlTestDefinition.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlTestRunnerTest.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/annotations/YamlTest.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/annotations/YamlTestConfiguration.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/executor/DefaultYamlTestExecutor.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/executor/EmptyYamlTestExecutor.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/executor/YamlTestExecutor.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/format/AnyPredicate.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/format/ExcludeRule.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/format/ExcludeSet.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/format/ExpressionPredicate.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/format/FunctionPredicate.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/format/SpELPredicate.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/format/TaggedPredicate.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/format/YamlTestFormat.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/resolver/ArbitraryObjectResolverFactory.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/resolver/CachingResolverBuilder.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/resolver/EmptyResolverFactory.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/resolver/FhirResolverFactory.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/resolver/HapiResolverFactory.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/resolver/ResolverBuilder.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/resolver/RuntimeContext.java
  fhirpath/src/test/resources/fhirpath-js/config.yaml
  fhirpath/src/test/resources/fhirpath-ptl/cases/search-params.yaml
  fhirpath/src/test/resources/logback-test.xml
  fhirpath/src/test/resources/search-params.txt
  utilities/src/main/java/au/csiro/pathling/errors/InvalidUserInputError.java
  utilities/src/main/java/au/csiro/pathling/errors/UnexpectedResponseException.java
  utilities/src/main/java/au/csiro/pathling/errors/UnsupportedFhirPathFeatureError.java
Labels: testing, fhirpath

#2449 Convert empty collection inputs to functions
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/MethodDefinedFunction.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/NamedFunction.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/resolver/BindingContext.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/resolver/FunctionInvocation.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/resolver/FunctionInvocationError.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/resolver/FunctionParameterResolver.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/function/FunctionParameterResolverTest.java
  fhirpath/src/test/resources/fhirpath-js/config.yaml
Labels: bug

#2439 Implement ANSI SQL Type hints
  encoders/src/main/scala/au/csiro/pathling/sql/PruneSyntheticFields.scala
  fhirpath/src/main/antlr4/au/csiro/pathling/views/ansi/TypesOfAnsiSql.g4
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/Materializable.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/BooleanCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/Collection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/DateCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/DateTimeCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/DecimalCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/EmptyCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/IntegerCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/StringCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/TimeCollection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/column/BinaryRepresentation.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/column/ColumnRepresentation.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/column/DecimalRepresentation.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/column/DefaultRepresentation.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/definition/fhir/FhirDefinitionContext.java
  fhirpath/src/main/java/au/csiro/pathling/sql/SqlFunctions.java
  fhirpath/src/main/java/au/csiro/pathling/sql/misc/DecimalToLiteral.java
  fhirpath/src/main/java/au/csiro/pathling/view/ColumnSelection.java
  fhirpath/src/main/java/au/csiro/pathling/view/ProjectedColumn.java
  fhirpath/src/main/java/au/csiro/pathling/view/ProjectionContext.java
  fhirpath/src/main/java/au/csiro/pathling/view/RequestedColumn.java
  fhirpath/src/main/java/au/csiro/pathling/views/Column.java
  fhirpath/src/main/java/au/csiro/pathling/views/ColumnTag.java
  fhirpath/src/main/java/au/csiro/pathling/views/FhirViewExecutor.java
  fhirpath/src/main/java/au/csiro/pathling/views/ansi/AnsiSqlDataTypeFactory.java
  fhirpath/src/main/java/au/csiro/pathling/views/ansi/AnsiSqlTypeParser.java
  fhirpath/src/main/java/au/csiro/pathling/views/ansi/ToDataTypeVisitor.java
  fhirpath/src/main/java/au/csiro/pathling/views/validation/UniqueTags.java
  fhirpath/src/main/java/au/csiro/pathling/views/validation/UniqueTagsValidator.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/FilteringAndProjectionFunctionsDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/sql/SqlFunctionsTest.java
  fhirpath/src/test/java/au/csiro/pathling/views/AnsiTypeHintingTest.java
  fhirpath/src/test/java/au/csiro/pathling/views/ColumnTest.java
  fhirpath/src/test/java/au/csiro/pathling/views/FhirViewValidationTest.java
  fhirpath/src/test/java/au/csiro/pathling/views/ansi/AnsiSqlTypeParserTest.java
  pom.xml
Labels: new feature

#2452 Minor fixes to the boolean collection evaluation
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/CollectionTransform.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/provider/FilteringAndProjectionFunctions.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/parser/Visitor.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/ExistenceFunctionsDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/SystemDslTest.java
  fhirpath/src/test/java/au/csiro/pathling/test/yaml/YamlSupport.java
  fhirpath/src/test/resources/fhirpath-js/config.yaml
Labels: bug

#2454 Log a warning when using type suffix on choice paths
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/collection/Collection.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/definition/ElementDefinition.java
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/definition/fhir/FhirElementDefinition.java
  fhirpath/src/test/java/au/csiro/pathling/fhirpath/dsl/SystemDslTest.java
Labels: new feature

#2451 Improve library API for Java and Scala users
  fhirpath/src/main/java/au/csiro/pathling/fhirpath/function/provider/JoinKeyFunctions.java
  fhirpath/src/main/java/au/csiro/pathling/views/Column.java
  fhirpath/src/main/java/au/csiro/pathling/views/ConstantConstructionException.java
  fhirpath/src/main/java/au/csiro/pathling/views/ConstantDeclaration.java
  fhirpath/src/main/java/au/csiro/pathling/views/ConstantDeclarationTypeAdapter.java
  fhirpath/src/main/java/au/csiro/pathling/views/ExecutionContext.java
  fhirpath/src/main/java/au/csiro/pathling/views/FhirView.java
  fhirpath/src/main/java/au/csiro/pathling/views/FhirViewBuilder.java
  fhirpath/src/main/java/au/csiro/pathling/views/FhirViewExecutor.java
  fhirpath/src/main/java/au/csiro/pathling/views/SelectClause.java
  fhirpath/src/main/java/au/csiro/pathling/views/SelectClauseBuilder.java
  fhirpath/src/main/java/au/csiro/pathling/views/WhereClause.java
  fhirpath/src/main/java/au/csiro/pathling/views/validation/AtMostOneNonNull.java
  fhirpath/src/main/java/au/csiro/pathling/views/validation/AtMostOneNonNullValidator.java
  fhirpath/src/main/java/au/csiro/pathling/views/validation/CompatibleUnionColumns.java
  fhirpath/src/main/java/au/csiro/pathling/views/validation/CompatibleUnionColumnsValidator.java
  fhirpath/src/main/java/au/csiro/pathling/views/validation/UniqueColumnNames.java
  fhirpath/src/main/java/au/csiro/pathling/views/validation/ValidName.java
  fhirpath/src/test/java/au/csiro/pathling/views/FhirViewExecutorTest.java
  fhirpath/src/test/java/au/csiro/pathling/views/FhirViewValidationTest.java
  library-api/src/main/java/au/csiro/pathling/library/PathlingContext.java
  library-api/src/main/java/au/csiro/pathling/library/io/source/AbstractSource.java
  library-api/src/main/java/au/csiro/pathling/library/io/source/QueryableDataSource.java
  library-api/src/main/java/au/csiro/pathling/library/query/FhirViewQuery.java
  site/docs/libraries/running-queries.md
  site/versioned_docs/version-7.2.0/roadmap.md
Labels: new feature

#2455 Add WireMock tests to bulk client functionality
  lib/python/pathling/bulk.py
  lib/python/pathling/datasource.py
  lib/python/pathling/spark.py
  lib/python/requirements/dev.txt
  lib/python/tests/conftest.py
  lib/python/tests/mockserver.py
  lib/python/tests/test_bulk.py
  lib/python/tests/test_datasource.py
  lib/python/tests/test_spark.py
Labels: new feature, python
